on:
  pull_request:
    types: [open, closed]

jobs:
  create-comment-in-asana-task-job:
    runs-on: ubuntu-latest
    name: Create a comment in Asana Task
    steps:
      - name: Create a comment
        uses: Asana/comment-on-task-github-action@v1.0
        id: createComment
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
          comment-text: "'{{PR_NAME}}' was {{PR_STATE}} ({{PR_URL}})"
      - name: Get status
        run: echo "Status is ${{ steps.createComment.outputs.status }}"
