on:
  pull_request:
    types: [opened, reopened]

jobs:
  create-comment-in-asana-task-job:
    runs-on: ubuntu-latest
    name: Create a comment in Asana Task
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Post a comment about the PR status
        uses: ./
        id: postComment
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
          comment-text: "{{PR_NAME}} is in {{PR_STATE}}"
      - name: Get status
        run: echo "PR status is ${{ steps.createComment.outputs.status }}"
