on:
  pull_request:
    types: [opened, reopened]

jobs:
  create-comment-in-asana-task-job:
    runs-on: ubuntu-latest
    name: Create a comment in Asana Task
    steps:
      - name: Create a comment
        uses: Asana/create-app-attachment-github-action@v1.0
        id: createComment
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
      - name: Get status
        run: echo "Status is ${{ steps.createComment.outputs.status }}"
